version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "80:8080"
    volumes:
      - "/home/jenkins_home:/var/jenkins_home"
    networks:
      - net
networks:
  net: